### ISSUE TITLE
Linux: Open location dialog causes servoshell to go into the background

### ISSUE THREAD

**Issue by tschneidereit** [paulrouget/servoshell#17]
At least when running from the shell, pressing `ctrl + l` shows the dialog, but also causes the terminal to be foregrounded, hiding servoshell.

**Comment by paulrouget** [comment]
I sent a fix to the owner of the tinyfiledialogs library.

I included the fix in my own fork and point Cargo.toml to my own fork for now.

Once it's fixed upstreamed, then picked up by tinyfiledialogs-rs, I will switch from my fork to the real repo.
