### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by shinglyu** [paulrouget/servoshell#3]
Sorry I don't know if this is right place to file bugs. But I failed to compile it on Linux (is it supported?) with nightly `rustc` (1.20.0). Here are the compile log:

```
cargo +nightly run
   Compiling multistr v0.2.1
   Compiling pkg-config v0.3.9
   Compiling language-tags v0.2.2
   Compiling toml v0.2.1
   Compiling bit-vec v0.4.3
   Compiling gcc v0.3.45
   Compiling encoding_index_tests v0.1.4
   Compiling same-file v0.1.3
   Compiling byteorder v1.0.0
   Compiling procedural-masquerade v0.1.1
   Compiling threadpool v1.3.2
   Compiling dtoa v0.4.1
   Compiling thread_profiler v0.1.1
   Compiling winapi v0.2.8
   Compiling fnv v1.0.5
   Compiling block v0.1.6
   Compiling rustc-demangle v0.1.4
   Compiling heapsize v0.3.8
   Compiling lzw v0.10.0
   Compiling owning_ref v0.2.4
   Compiling mac v0.1.1
   Compiling libc v0.2.21
   Compiling precomputed-hash v0.1.0
   Compiling lazy_static v0.2.4
   Compiling slab v0.3.0
   Compiling adler32 v1.0.0
   Compiling regex-syntax v0.4.0
   Compiling glob v0.2.11
   Compiling simd v0.2.0
   Compiling webrender v0.36.0 (https://github.com/servo/webrender#7b499ba9)
   Compiling string_cache_shared v0.3.0
   Compiling script_plugins v0.0.1 (https://github.com/servo/servo.git?rev=93a513c06f#93a513c0)
   Compiling semver v0.1.20
   Compiling sha1 v0.2.0
   Compiling backtrace v0.3.0
error[E0599]: no method named `fn_args` found for type `&rustc::ty::TyS<'_>` in the current scope
   --> /home/shinglyu/.cargo/git/checkouts/servo-12bfca331f128de3/93a513c/components/script_plugins/unrooted_must_root.rs:145:56
    |
145 |             for (arg, ty) in decl.inputs.iter().zip(ty.fn_args().0.iter()) {
    |                                                        ^^^^^^^

error[E0599]: no method named `fn_ret` found for type `&rustc::ty::TyS<'_>` in the current scope
   --> /home/shinglyu/.cargo/git/checkouts/servo-12bfca331f128de3/93a513c/components/script_plugins/unrooted_must_root.rs:152:42
    |
152 |                 if is_unrooted_ty(cx, ty.fn_ret().0, false) {
    |                                          ^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `script_plugins`.
warning: build failed, waiting for other jobs to finish...
error: build failed
****
```

**Comment by paulrouget** [comment]
Not working on Linux yet.

Dump from a recent email about how to compile servoshell:

# Compilation:

cargo 0.20.0-nightly (bbfe9b3a9 2017-06-05)

./demo/servoshell -> https://github.com/paulrouget/servoshell -> #tabs_demo
./demo/servo -> https://github.com/paulrouget/servo -> #api_next_next
./demo/MMTabBarView -> https://github.com/dparnell/MMTabBarView -> #master


in ./demo/MMTabBarView/MMTabBarView (it's a library to build tabs):

/usr/bin/xcodebuild -target MMTabBarView -configuration Release

Then copy the library in servoshell:

cp -r ./demo/MMTabBarView/MMTabBarView/build/Release/MMTabBarView.framework
 ./demo/servoshell/macos/framework/

in ./demo/servoshell:

cargo build --release

then, after each build, you need to do:

install_name_tool -add_rpath
ABSOLUTE_PATH_TO/demo/servoshell/macos/framework
./demo/servoshell/target/release/servoshell

cargo run --release

# Usage

Works like any regular browser.
When there's only one tab, there is no tabbar.
To create a new tab: Cmd+T
Using the urlbar to search a website should work, as in, it loads duckduckgo.
Don't forget to click on the webpage to unfocus the urlbar (not automatic yet).

# Limitations:
We can't close tabs yet. Clicking on the tabstrip doesn't work. You
need to use ctrl-tab and ctrl-shift-tab to navigate.
Scrolling only properly works on the first tab.

**Comment by shinglyu** [comment]
So it's because of the platform-specific capabilities? If I want to help enabling it on Linux, where should I start?

**Comment by paulrouget** [comment]
>  So it's because of the platform-specific capabilities? If I want to help enabling it on Linux, where should I start?

90% of this project is Cocoa code. So basically, you would need to rewrite everything in QT/GTK.

I think it's too early to start writing Linux code. We are still experimenting with ServoShell and we don't know yet the exact scope of this project.

**Comment by minecrawler** [comment]
Why not switch it over to winit or similar, which is cross-platform?

**Comment by paulrouget** [comment]
> Why not switch it over to winit or similar, which is cross-platform?

winit/glutin don't include any widgets or any fine OS integration.

Actually, there's a branch here that uses winit (`with_glutin_and_no_xib`) but there is really no value in using it as 90% of the code is Cocoa.

**Comment by paulrouget** [comment]
The best we can do with winit/glutin is what we find in `/ports/servo/`.

**Comment by paulrouget** [comment]
Now it should work on Windows and Linux.

**Comment by lqd** [comment]
@paulrouget not quite, https://github.com/paulrouget/servoshell/commit/e6aca10f02f34f5155eb54767994ae5866662f80 prevented xcodebuild, but ibtool in build_nibs will still fail :)

**Comment by paulrouget** [comment]
@lqd good catch. I pushed a fix.
